spring.application.name=demo
#server.port=8090   #default => 8080

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java

spring.thymeleaf.cache=false
