GET http://localhost:8080/api/users
Accept: application/json


### regist
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "Kim1234",
  "age": 20
}

### get a user
GET http://localhost:8080/api/users/4

### update user
PATCH http://localhost:8080/api/users/2
Content-Type: application/json

{
  "name": "New"
}


### delete
DELETE http://localhost:8080/api/users/2
